### ISSUE TITLE
Homepage should sorted by the newest

### ISSUE THREAD

**Issue by mazipan** [zakiego/baku-hantam#12]
The homepage shows baku hantam cases but seems sorted by the creation date. It's kinda weird to scroll down just to get the latest drama.

It's better to reverse the order. Show the newest first.

![Screenshot_20240827-192144_Chrome.jpg](https://github.com/user-attachments/assets/398698f6-4847-4f7d-a86f-f0d64f5148c8)

**Comment by zakiego** [comment]
Thank you for your feedback. This issue is due to the ongoing migration process, and there are many things that need to be organized

What I'm considering is how to determine the "date" for each topic. Should it be the date of the first tweet for each topic, or the date when the topic was last updated?

**Comment by mazipan** [comment]
I assumed it should the oldest tweet from each topic.

**Comment by mazipan** [comment]
If it's too complicated to determine the date by the tweet's date, then just use the creation date of the topic itself.

**Comment by mazipan** [comment]
Sepertinya sudah ditambahkan fitur sort, bisa ditutup isu ini
